# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Quick links
email: matt@mattbramlage.com
description: >- # this means to ignore newlines until "baseurl:"
  Matt's short links
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://matt.directory" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - webapp

collections:
  get:
    output: true
    permalink: /:collection/:name

  short:
    output: true
    permalink: /:name

  themed_collection:
    output: true
    permalink: /th/:name

  # This is implemented as in matt.directory/pw as a public file with the JS redirect logic in it.
  # This is the entry point for password protected pages.
  semi_private:
    output: true
    permalink: /pw/:name

  private_matt:
    # This is your standard simple password
    output: true
    #IMPORTANT: if you change the password, which changes the hash,
    #ALSO CHANGE THIS IN ROBOTS.TXT to avoid crawling of this directory.
    permalink: /43fc89395ef02296438e189c8aaacc0ab082199d9038e0705421229c667b42ce/:name


permalink: none

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
