name: /l Daily Runs
run-name: ${{ github.actor }} is triggering all daily scripts
on: 
  schedule:
    # 12:30 in UTC is 4:30 AM in PST
    - cron: 30 12 * * *
  workflow_dispatch:
jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - env: 
          GOOGLE_CLOUD_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
      - run: echo "🎬 beginning DAILY runs"
      - run: echo "🎉 The job was triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3
          cache: 'pipenv'
      - name: Install pipenv
        run: pip install pipenv
      - name: Install deps
        run: |
          pipenv install
      - name: List files in the scripts directory and run sequentially from home dir using abspath.
        run: |
          JOBS=$(find ${{ github.workspace }}/runners/daily -name "*.py" -not -iname "_*" -executable | sort)
          echo $JOBS
          for J in $JOBS; do
            echo "RUNNNING $J";
            pushd ${{ github.workspace }}; pipenv run $J; popd
          done
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Git commit new dailies.json
        run: |
          git config --global user.name "Matt Bramlage"
          git config --global user.email "praecipula@users.noreply.github.com"
          git add page_cache
          git commit -a -m "Auto commit of dailies.json from github actions"
          git push
